on: [push, pull_request]

name: Continuous integration

jobs:
  Tests:
    name: Tests
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        toolchain:
          - 1.41.1
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Crate
        uses: actions/checkout@v2
      - name: Checkout Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Running tests on ${{ matrix.toolchain }}
        run: cargo test --verbose --all-features
